logging:
  level:
    .: error
    org.springframework: ERROR
    com.mkyong: ERROR


spring:
  profiles:
    active: "prod"
  main:
    banner-mode: "off"
  couchbase:
    bootstrap-hosts: u-srv-hrd
    bucket:
      name: sports
      password: password

name: Default name

cb:
  server:
    email: default@ukr.net
    name: u-srv-hrd
    bucket:
      name: sports
      password: password


---

spring:
  profiles: dev
server:
  email: dev@ukr.net
  cluster:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3
name: Developer Setup

---

spring:
  profiles: prod
server:
  email: prod@ukr.net
  cluster:
    - ip: 192.168.0.1
      path: /app1
    - ip: 192.168.0.2
      path: /app2
    - ip: 192.168.0.3
      path: /app3
name: My Cool App